Fix: Correct English Grammar
PurplePalette/sonolus-audio-server pull request #11
Opened 2022-06-20 13:37 UTC by Kokohachi

Fixed English grammar

2022-06-20 13:40 UTC, sevenc-nanashi requested changes

2022-06-20 13:40 UTC, sevenc-nanashi commented on src/main.py
> +            return JSONResponse(content={"message": "The audio file must be longer than 5 seconds"}, status_code=400)
```suggestion
            return JSONResponse(content={"message": "The audio file must be longer than 5 seconds."}, status_code=400)
```

2022-07-23 13:30 UTC, Dosugamea requested changes
唐突ながらマージしていなかったのでレビューした。
こういう方針なので 申し訳ないが変更お願い!!

2022-07-23 13:30 UTC, Dosugamea commented on src/main.py
> +            return JSONResponse(content={"message": "The audio file must be longer than 5 seconds."}, status_code=400)
APIの応答メッセージは 最後に ピリオドを入れない方針で統一していきたいです

2022-07-23 13:30 UTC, Dosugamea commented on src/main.py
> +            return JSONResponse(content={"message": "The audio file is too long."}, status_code=400)
APIの応答メッセージは 最後に ピリオドを入れない方針で統一していきたいです

2022-08-11 07:32 UTC, Kokohachi commented on src/main.py
> +            return JSONResponse(content={"message": "The audio file must be longer than 5 seconds."}, status_code=400)
Updateしました、これで治せてますかね

2022-08-11 07:33 UTC, Kokohachi commented on src/main.py
> +            return JSONResponse(content={"message": "The audio file is too long."}, status_code=400)
Updateしました、治せてますかね

2022-08-11 07:45 UTC, sevenc-nanashi approved these changes

2022-09-18 08:53 UTC, Dosugamea approved these changes

2022-09-18 08:54 UTC, merged